<a href="https://colab.research.google.com/github/nayem-uddin/udemy-python-course/blob/main/Level_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Mastering NumPy**

In [ ]:
import numpy as np

Let's make a numpy array, which is similar to a list.

In [ ]:
a_np = np.array([1,2,3,4,5])

In [ ]:
type(a_np)

numpy.ndarray

Instead of using a loop, we can just use simple operators to perform element-wise mathematical operations on a numpy array.

In [ ]:
a_np +  1 # add 1 to each element

array([2, 3, 4, 5, 6])

Let's make a two-dimensional array.

In [ ]:
array_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
array_2d+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
array_2d[0]+1

array([2, 3, 4])

In [ ]:
array_2d.shape # rows, columns

(3, 3)

In [ ]:
array_2d.size # no. of total elements

9

In [ ]:
array_2d.ndim # no. of dimensions

2

To convert a list into a numpy array, we can do the following.

In [ ]:
a=list(range(5)) # just defined a random list
a_num = np.array(a) # converted it into a numpy array
a_num

array([0, 1, 2, 3, 4])

### **Arrays Data Type**

In [ ]:
a_np.dtype

dtype('int64')

As it has only integers in it, the data type is "int64".

In [ ]:
array_2d=np.array([
    [1,2,3],
    [4,"Hello",6],
    [7,8,9]
])

In [ ]:
array_2d.dtype

dtype('<U21')

It has multiple data type; "U" means "ununified".

In [ ]:
array_2d=np.array([
    [1,2,3],
    [4,"5",6],
    [7,8,9]
],dtype=np.float64) # to convert the whole array into a unified array

In [ ]:
array_2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

### **Numpy Array Creation Methods**

np.full()

In [ ]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

np.ones()

In [ ]:
ones = np.ones((4,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

np.zeros()

In [ ]:
zeros = np.zeros((4,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

np.arange(): This functions similar to "range".

In [ ]:
arange = np.arange(10,100,10) # up to, but not including, 100
arange

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(10,101,10) # up to, but not including, 101

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

np.linspace()

In [ ]:
lines = np.linspace(10,100,10) # 10 elements starting from 10 and up to, and including, 100
lines

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
lines = np.linspace(10,100,40)
lines

array([ 10.        ,  12.30769231,  14.61538462,  16.92307692,
        19.23076923,  21.53846154,  23.84615385,  26.15384615,
        28.46153846,  30.76923077,  33.07692308,  35.38461538,
        37.69230769,  40.        ,  42.30769231,  44.61538462,
        46.92307692,  49.23076923,  51.53846154,  53.84615385,
        56.15384615,  58.46153846,  60.76923077,  63.07692308,
        65.38461538,  67.69230769,  70.        ,  72.30769231,
        74.61538462,  76.92307692,  79.23076923,  81.53846154,
        83.84615385,  86.15384615,  88.46153846,  90.76923077,
        93.07692308,  95.38461538,  97.69230769, 100.        ])

### **Operations with arrays**

In [ ]:
l1 = [1, 2, 3, 4, 5]
l2 = [6, 7, 8, 9, 10]

a1 = np.array(l1)
a2 = np.array(l2)

In [ ]:
a1 + 5

array([ 6,  7,  8,  9, 10])

In [ ]:
(a1 + a2) * 5

array([35, 45, 55, 65, 75])

In [ ]:
a1_new = np.array([1, 2, 3])
a2_new = np.array([[1], [2]])

In [ ]:
a1_new + a2_new

array([[2, 3, 4],
       [3, 4, 5]])

[1, 2, 3] + [1] = [2, 3, 4] <br>
[1, 2, 3] + [2] = [3, 4, 5]

In [ ]:
a2_new.shape

(2, 1)

In [ ]:
(a1_new + a2_new).shape

(2, 3)

In [ ]:
np.sqrt(a1_new)

array([1.        , 1.41421356, 1.73205081])

# Rules of Broadcasting

Broadcasting follows a set of rules to determine the interaction between the two arrays:

1. **Dimension Compatibility**: Starting from the trailing dimensions, the dimensions of the arrays must either be the same, or one of them must be 1.
  
2. **Stretching**: If the sizes along a dimension are not the same, NumPy will try to stretch the array with size 1 along that dimension to match the other size.

3. **Result Shape**: The shape of the resulting array is the maximum size along each dimension from the input arrays.

### Scalar and One-dimensional Array


In [ ]:
arr = np.array([1, 2, 3])

res_arr = arr + 5

In [ ]:
res_arr

array([6, 7, 8])


### Two-dimensional Array and One-dimensional Array



In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.ones((3))

print(arr1d)

[1. 1. 1.]


In [ ]:
arr2d + arr1d

array([[2., 3., 4.],
       [5., 6., 7.]])



### Broadcasting Two Arrays with Different Shapes



In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])

A.shape

(3, 2)

In [ ]:
B = np.array([1, 2])

In [ ]:
A + B

array([[2, 4],
       [4, 6],
       [6, 8]])

But it won't work for the following case.


In [ ]:
b = np.array([1, 2, 3])

In [ ]:
A + b

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

This is because it can't perform element-wise operation in this case.


But the following case will succeed.

In [ ]:
a = np.array([[1], [3], [5]])

In [ ]:
a + b

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])


## Practical Applications

1. **Data Normalization**: Broadcasting can be used to normalize datasets by subtracting the mean and dividing by the standard deviation.
  
2. **Image Manipulation**: You can use broadcasting to apply filters or adjustments to RGB channels in images.

3. **Mathematical Modeling**: In simulations or mathematical models, broadcasting can simplify the code and make it more efficient.

## Caveats and Limitations

1. **Implicitness**: Broadcasting can make code less explicit, which may lead to bugs if you're not careful about array shapes.

2. **Memory Efficiency**: While broadcasting saves memory by avoiding explicit replication of data, it's still possible to run into memory issues with very large arrays.


#  Indexing and Slicing - Accessing Array Elements in NumPy

## Introduction


---

## Part 1: Basic Indexing









In [ ]:
exam_scores = np.array([90, 85, 77, 92])

In [ ]:
print("First student's score is: ", exam_scores[0])

First student's score is:  90


## Part 2: Multidimensional Indexing
    - Accessing elements in 2D and 3D arrays.
    - Using row and column indices.


In [ ]:
sales_data = np.array([
    [200, 220, 250],
    [210, 230, 275],
    [190, 205, 235]
]) # three rows represent the data of January, February, and March, respectively

In [ ]:
sales_data[0] # the data of January

array([200, 220, 250])

In [ ]:
sales_data[0][0] # First product of January

200

Similar result can be obtained as follows.

In [ ]:
sales_data[0, 0]

200

In [ ]:
sales_data = np.array([
    [[200, 222], 220, 250],
    [210, 230, 275],
    [190, 205, 235]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 3) + inhomogeneous part.

Well, I don't know why, but the code in the above cell is not working in my case, but the colab file provided by the course providers from where I've taken this code has the message below, but still works well. <br>
< ipython-input-9-be08a371c6c6 >:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  sales_data = np.array([

## Part 3: Basic Slicing
    - How to slice arrays to get subarrays.
    - Using the `start:stop:step` notation.


In [ ]:
monthly_revenue = np.array([200, 220, 250, 275, 344, 350, 320, 400, 420, 450, 450])

In [ ]:
monthly_revenue[4::] # from the 5th element to the last

array([344, 350, 320, 400, 420, 450, 450])

In [ ]:
monthly_revenue[4::2] # from the 5th element to the last, skipping one element at each step (step = 2)

array([344, 320, 420, 450])

In [ ]:
monthly_revenue[::2] # from the first element to the last, skipping every second

array([200, 250, 344, 320, 420, 450])

In [ ]:
monthly_revenue[::-1] # reverse

array([450, 450, 420, 400, 320, 350, 344, 275, 250, 220, 200])

## Part 4: Advanced Slicing Techniques
    - Using boolean arrays for indexing.
    - Combining slicing with conditional statements.


In [ ]:
avg = np.mean(monthly_revenue)
avg

334.45454545454544

The following is an example of conditional accessing of the point. In the following case, we want to get the monthly revenue above the average.

In [ ]:
monthly_revenue[monthly_revenue > avg]

array([344, 350, 400, 420, 450, 450])

Note that only the condition gives up an array of "True"s and "False"s, from which we apparently can't have any useful information.

In [ ]:
monthly_revenue > avg

array([False, False, False, False,  True,  True, False,  True,  True,
        True,  True])

So, when we use the condition as an index, only the values in the array corresponding the "True"s are returned.

## Part 5: Important Caveats and Best Practices
    - Mention that slices are views, not copies.
    - The importance of being aware of data types when slicing and indexing.


In [ ]:
monthly_revenue[monthly_revenue > avg]

array([344, 350, 400, 420, 450, 450])

The action we've done in the above cell is just "showing" us an array based on the condition we provided, not modifying the original array. We can store that array in a new variable as follows, which enables us to modify the new array we get.

In [ ]:
monthly_revenue_ab_avg = monthly_revenue[monthly_revenue > avg]

In [ ]:
monthly_revenue_ab_avg

array([344, 350, 400, 420, 450, 450])

## **Exercise 10.1**

# Mini Project: 1D Slicing and Indexing with NumPy

## Objective

In this mini-project, you will practice 1D slicing and indexing techniques using NumPy. We'll work on a dataset that represents monthly sales data for a retail store and perform various data manipulation tasks.

## Dataset

Let's assume we have a 1D NumPy array that represents the monthly sales for a retail store for one year, in thousands of dollars.



In [ ]:
monthly_sales = np.array([200, 220, 250, 275, 300, 320, 350, 370, 400, 420, 450, 475])


## Tasks

### Task 1: Basic Indexing

1. Access and print the sales data for January (the first month).
2. Access and print the sales data for December (the last month).








In [ ]:
print("January info:",monthly_sales[0])
print("December info:",monthly_sales[-1])

January info: 200
December info: 475


### Task 2: Access Quarterly Data

1. Extract and print the sales data for each quarter (Q1, Q2, Q3, and Q4).

In [ ]:
print(monthly_sales[:3])
print(monthly_sales[3:6])
print(monthly_sales[6:9])
print(monthly_sales[9:])

[200 220 250]
[275 300 320]
[350 370 400]
[420 450 475]


### Task 3: Modify Sales Data

1. Assume that there was an error in the data entry for the month of April. The correct sales figure is $280,000. Update this value in the array.
2. Print the updated array to confirm the change.

In [ ]:
monthly_sales[3]=280
print(monthly_sales)

[200 220 250 280 300 320 350 370 400 420 450 475]


### Task 4: Summer Sales

1. Extract and print the sales data for the summer months (June, July, August).
2. Calculate and print the average sales for the summer months.

In [ ]:
summer_months=monthly_sales[5:8]
avg_summer=np.mean(summer_months)
print(summer_months)
print(avg_summer)

[320 350 370]
346.6666666666667


### Task 5: Above Average Months

1. Calculate the average monthly sales for the entire year.
2. Identify and print the months where the sales were above average.

In [ ]:
avg = np.mean(monthly_sales)
print(monthly_sales[monthly_sales > avg])

[350 370 400 420 450 475]


# Python Loops vs Vectorization in NumPy

## Introduction

---

## Part 1: Understanding Python Loops







In [ ]:
daily_users = [200, 220, 250, 275]

avg_users = 0
for e in daily_users:
  avg_users += e

print(avg_users / len(daily_users))

236.25


To find average user, this is the common approach. But Python loops are slow, and we may need vectorization if we want our code to execute faster.

## Part 2: Introduction to Vectorization
  - What vectorization is and why it's important.
  - Brief explanation of how NumPy uses vectorized operations.


In [ ]:
du_np = np.array(daily_users)

print(np.mean(du_np))

## Part 3: Performance Comparison

Let's check if vectorization really works faster.

In [ ]:
large_array = np.random.randint(1, 100, size=10000000)

In [ ]:
import time

start_time = time.time()
avg = 0
for e in large_array:
  avg += e
print(avg / 10000000)
end_time = time.time()
print(end_time - start_time)

50.0047124
2.5775675773620605


In [ ]:
start_time = time.time()
print(np.mean(large_array))
end_time = time.time()
print(end_time - start_time)

50.0047124
0.023087263107299805


## **Exercise 10.2**
# Exercise: Vectorize a Given Python Loop

## Objective

In this exercise, you'll practice converting a Python loop that performs a mathematical operation into a vectorized version using NumPy. By doing so, you'll learn to write more efficient and cleaner code.

## Scenario

Imagine you're working with a dataset containing the monthly sales data for a retail business. You want to apply a 10% discount to each monthly sales figure to calculate the new sales numbers.



## Task 1: Using Python Loop

1. Create a list called `monthly_sales` containing 12 integers, each representing the sales for a month.
2. Initialize an empty list called `discounted_sales`.
3. Loop through each value in `monthly_sales`, apply a 10% discount, and append the result to `discounted_sales`.


In [ ]:
monthly_sales = [1000, 1050, 1200, 1100, 1500, 2000, 1900, 1300, 1800, 1700, 1600, 1400]
discounted_sales = []
for i in monthly_sales:
  discounted_sales.append(i*0.9)
print(monthly_sales)
print(discounted_sales)

[1000, 1050, 1200, 1100, 1500, 2000, 1900, 1300, 1800, 1700, 1600, 1400]
[900.0, 945.0, 1080.0, 990.0, 1350.0, 1800.0, 1710.0, 1170.0, 1620.0, 1530.0, 1440.0, 1260.0]



## Task 2: Using NumPy Vectorization

### Instructions

1. Convert the `monthly_sales` list into a NumPy array.
2. Use NumPy's vectorized operations to apply a 10% discount to each value.
3. Store the result in a new NumPy array called `discounted_sales_np`.


In [ ]:
monthly_sales = np.array(monthly_sales)
discounted_sales_np = monthly_sales*0.9
print(monthly_sales)
print(discounted_sales_np)

[1000 1050 1200 1100 1500 2000 1900 1300 1800 1700 1600 1400]
[ 900.  945. 1080.  990. 1350. 1800. 1710. 1170. 1620. 1530. 1440. 1260.]


# Universal Functions - The Power of UFuncs in NumPy

## Introduction



## Part 1: What are UFuncs?
    - Definition and characteristics of UFuncs.
    - UFuncs allow for element-wise operations on arrays.













In [ ]:


product_prices = np.array([20, 25, 33, 37, 40])

In [ ]:
print("Discountinued prices", np.sqrt(product_prices))

Discountinued prices [4.47213595 5.         5.74456265 6.08276253 6.32455532]


## Part 2: Basic UFuncs for Arithmetic Operations
    - Common arithmetic operations like addition, subtraction, multiplication, and division.


In [ ]:
revenue = np.array([4000, 4500, 4000])
expenses = np.array([2000, 1500, 2500])

print(np.subtract(revenue, expenses))
revenue - expenses

[2000 3000 1500]


array([2000, 3000, 1500])


## Part 3: Trigonometric and Logarithmic UFuncs
    - Trigonometric functions like `np.sin`, `np.cos`.
    - Logarithmic functions like `np.log`, `np.exp`.

In [ ]:
principal = 1000
rate = 0.05

years = np.array([1, 2, 3, 4, 5])

In [ ]:
compound_interest = np.multiply(principal, np.exp(np.multiply(rate, years))) # this is similar to "principal * np.exp(rate * years)"

In [ ]:
compound_interest

array([1051.27109638, 1105.17091808, 1161.83424273, 1221.40275816,
       1284.02541669])

## Part 4: Comparison and Logical UFuncs
    - Comparison UFuncs like `np.greater`, `np.less_equal`.
    - Logical UFuncs like `np.logical_and`, `np.logical_or`.


In [ ]:
revenue = np.array([4000, 4500, 4000])
expenses = np.array([2000, 1500, 2500])

In [ ]:
expenses[np.less_equal(expenses, 2000)] # this is similar to "expenses[expenses <= 2000]"

array([2000, 1500])

## Part 5: Custom UFuncs
    - Creating custom UFuncs using `np.vectorize`.
Instead of using "map", we can use vectorization.

In [ ]:
# define a function
def calculate_nps(score):
  if score >= 9:
    return "Promoter"
  elif score >= 7:
    return "Passive"
  else:
    return "Detractor"

In [ ]:
# make a vectorized version of that version
nps_ufunc = np.vectorize(calculate_nps)

In [ ]:
# just an array is built here, skip if you've already built your array
scores = np.array([9, 8, 6, 7, 6])

In [ ]:
# apply the vectorized function on your array
nps_ufunc(scores)

array(['Promoter', 'Passive', 'Detractor', 'Passive', 'Detractor'],
      dtype='<U9')

# Conditional Selection - Choosing with Conditions in NumPy

## Introduction

---

## Part 1: Basic Conditional Selection
- **Bullet Points**:
    - Introduction to the `np.where` function for basic conditional operations.
    - Real-world Example: Determining which employees are eligible for a bonus based on their performance scores.




In [ ]:
scores = np.array([85, 90, 78, 92, 88])

In [ ]:
np.where(scores > 80) # to get the indices of the values greater than 0

(array([0, 1, 3, 4]),)

In [ ]:
eligibility = np.where(scores > 85, "Yes", "No")
print(eligibility)

['No' 'Yes' 'No' 'Yes' 'Yes']


## Part 2: Multiple Conditions
    - Using logical operators like `&` (and), `|` (or) to combine conditions.
Multiple conditions are seperated using parentheses and related using logical operators.


In [ ]:
eligibility = np.where((scores < 87) & (scores > 80) | (scores > 90) , "Yes", "No")
print(eligibility)

['Yes' 'No' 'No' 'Yes' 'No']


## Part 3: Filtering Arrays
    - Using boolean indexing to filter arrays based on conditions.


In [ ]:
scores[(scores < 87) | (scores > 90)]

array([85, 78, 92])

## Part 4: Nested Conditions
    - Using nested `np.where` for more complex conditional logic.


In [ ]:
np.where(scores < 80 , "Yes", np.where(scores > 90 , "Yes", "No"))

array(['No', 'No', 'Yes', 'Yes', 'No'], dtype='<U3')

# Reshaping Arrays - Changing Dimensions and Size in NumPy

## Introduction

---

## Part 1: The `reshape` Method
    - Introduction to the `np.reshape` function for changing array dimensions.



In [ ]:
data = np.random.randint(10, 100, 100)
data

array([36, 65, 25, 99, 55, 61, 84, 54, 70, 89, 80, 99, 97, 39, 72, 70, 85,
       40, 39, 13, 54, 17, 61, 44, 33, 26, 57, 84, 40, 49, 74, 93, 82, 34,
       63, 88, 52, 70, 18, 90, 57, 54, 61, 36, 47, 36, 73, 81, 54, 76, 52,
       31, 88, 41, 97, 22, 26, 62, 18, 24, 61, 22, 61, 36, 10, 84, 51, 60,
       75, 94, 93, 38, 57, 97, 69, 92, 59, 86, 23, 24, 34, 30, 41, 48, 86,
       50, 75, 30, 57, 76, 89, 50, 54, 98, 86, 55, 97, 57, 66, 25])

In [ ]:
data = data.reshape(10, 10)
print(data)

[[36 65 25 99 55 61 84 54 70 89]
 [80 99 97 39 72 70 85 40 39 13]
 [54 17 61 44 33 26 57 84 40 49]
 [74 93 82 34 63 88 52 70 18 90]
 [57 54 61 36 47 36 73 81 54 76]
 [52 31 88 41 97 22 26 62 18 24]
 [61 22 61 36 10 84 51 60 75 94]
 [93 38 57 97 69 92 59 86 23 24]
 [34 30 41 48 86 50 75 30 57 76]
 [89 50 54 98 86 55 97 57 66 25]]


## Part 2: Flattening Arrays
    - Using `ravel()` and `flatten()` to convert multi-dimensional arrays to 1D arrays.


In [ ]:
data2 = np.random.randint(10, 100, 25)
data2 = data2.reshape(5, 5)

In [ ]:
data2.shape

(5, 5)

`ravel` modifies the original array when a change is made. However, `flatten` doesn't do so.

In [ ]:
data3 = data2.flatten()
print(data3)

[87 30 93 17 61 41 69 46 19 18 20 30 13 66 57 92 86 33 18 13 29 79 48 90
 36]


In [ ]:
data3[10] = 10000
print(data3)
print(data2)

[   87    30    93    17    61    41    69    46    19    18 10000    30
    13    66    57    92    86    33    18    13    29    79    48    90
    36]
[[87 30 93 17 61]
 [41 69 46 19 18]
 [20 30 13 66 57]
 [92 86 33 18 13]
 [29 79 48 90 36]]


In [ ]:
data4 = data2.ravel()
print(data4)

[87 30 93 17 61 41 69 46 19 18 20 30 13 66 57 92 86 33 18 13 29 79 48 90
 36]


In [ ]:
data4[10] = 10000
print(data4)
print(data2)

[   87    30    93    17    61    41    69    46    19    18 10000    30
    13    66    57    92    86    33    18    13    29    79    48    90
    36]
[[   87    30    93    17    61]
 [   41    69    46    19    18]
 [10000    30    13    66    57]
 [   92    86    33    18    13]
 [   29    79    48    90    36]]


## Part 3: Transposing Arrays
    - Using `np.transpose` or `.T` to swap array dimensions.



In [ ]:
data_T = np.random.randint(10, 100, 20).reshape(2, 10)
print(data_T)

[[99 68 11 20 98 82 26 82 61 40]
 [29 16 86 86 91 20 95 35 22 72]]


In [ ]:
print(data_T.T)

[[99 29]
 [68 16]
 [11 86]
 [20 86]
 [98 91]
 [82 20]
 [26 95]
 [82 35]
 [61 22]
 [40 72]]


## Part 4: Resizing Arrays
    - Using `np.resize` to change the size of an array.



In [ ]:
np.resize(data_T, (5, 4))

array([[99, 68, 11, 20],
       [98, 82, 26, 82],
       [61, 40, 29, 16],
       [86, 86, 91, 20],
       [95, 35, 22, 72]])

When the desired dimension doesn't match the no. of elements in the original array, `resize` will continue adding new values or stop adding further values based on the condition, unlike `reshape`, which shows error message in both cases.

In [ ]:
np.resize(data_T, (5, 6))

array([[99, 68, 11, 20, 98, 82],
       [26, 82, 61, 40, 29, 16],
       [86, 86, 91, 20, 95, 35],
       [22, 72, 99, 68, 11, 20],
       [98, 82, 26, 82, 61, 40]])


## Part 5: Concatenating and Splitting Arrays
    - Using `np.concatenate`, `np.vstack`, and `np.hstack` for joining arrays.
    - Using `np.split` for breaking an array into smaller chunks.


In [ ]:
data_1t = np.array([100, 1500])
data_2t = np.array([200, 2500])

In [ ]:
np.concatenate((data_1t, data_2t))

array([ 100, 1500,  200, 2500])

In [ ]:
np.vstack((data_1t, data_2t)) # vstack means vertical stack

array([[ 100, 1500],
       [ 200, 2500]])

In [ ]:
np.hstack((data_1t, data_2t)) # hstack means horizontal stack


array([ 100, 1500,  200, 2500])

# Handling Missing Values Using NumPy

## Introduction


## Part 1: Understanding Missing Values
    - Types of missing values: completely missing, partially missing, or incorrectly entered.
    - Common reasons for missing values: data entry errors, unavailability of information, etc.


In [ ]:
customer_data = np.array([100, 150, np.nan, 200, 175])

## Part 2: Identifying Missing Values in NumPy
    - Using `np.isnan()` to identify missing values.
    - Counting the number of missing values in an array.



In [ ]:
missing_values = np.isnan(customer_data)
missing_values

array([False, False,  True, False, False])

In [ ]:
print("We have this many missing values: ", np.sum(missing_values)) # np.sum here counts the no. of true values

We have this many missing values:  1


## Part 3: Replacing Missing Values
    - Using `np.nan_to_num()` to replace missing values with zero.
    - Replacing missing values with mean, median, or a specific value using `np.nanmean()` and `np.nanmedian()`.



In [ ]:
zero_filled = np.nan_to_num(customer_data)
zero_filled

array([100., 150.,   0., 200., 175.])

In [ ]:
mean_data = np.nanmean(customer_data)
mean_data

156.25

In [ ]:
data_mean_filled = np.where(np.isnan(customer_data), mean_data, customer_data) # to replace the nan values with the mean of the data
data_mean_filled

array([100.  , 150.  , 156.25, 200.  , 175.  ])

## Part 4: Deleting Missing Values
    - Deleting rows with missing values using `np.isnan()` and array slicing.
    - When to delete data: caution about losing information.



In [ ]:
data_without_nan = customer_data[~np.isnan(customer_data)]
data_without_nan

array([100., 150., 200., 175.])

## Part 5: Forward and Backward Filling of Missing Values
    - Using methods to fill missing values based on neighboring elements.

In [ ]:
# creating a copy of the given data not to modify the original one
copy_of_cd = np.copy(customer_data)
copy_of_cd

array([100., 150.,  nan, 200., 175.])

In [ ]:
# finding the indices of the nan values
mask = np.isnan(copy_of_cd)
mask

array([False, False,  True, False, False])

In [ ]:
# shifting each of the data
np.roll(copy_of_cd, shift=-1)

array([150.,  nan, 200., 175., 100.])

In [ ]:
np.roll(copy_of_cd, shift=-1)[mask]

array([200.])

In [ ]:
# replacing the nan value with its neighborhood value
copy_of_cd[mask] = np.roll(copy_of_cd, shift=-1)[mask]
copy_of_cd

array([100., 150., 200., 200., 175.])

# File Handling - Saving and Loading NumPy Arrays

## Introduction


---

## Part 1: Saving Arrays with `np.save` and `np.savez`
    - Introduction to the `np.save` function for saving single arrays.
    - Use of `np.savez` for saving multiple arrays.








In [ ]:
age = np.array([18, 25, 33, 44, 22, 45])

In [ ]:
np.save("age.npy",age) # this will save the "age" array in the "files" section (find on the sidebar) under the name "age.npy"

## Part 2: Loading Arrays with `np.load`
    - Using the `np.load` function to load saved arrays.



In [ ]:
loaded_age = np.load("age.npy")

In [ ]:
loaded_age

array([18, 25, 33, 44, 22, 45])

## Part 3: Saving Text Files with `np.savetxt`
    - Introduction to `np.savetxt` for saving arrays as text files.

In [ ]:
np.savetxt("age.txt", loaded_age, delimiter=",") # save the "loaded_age" array under a text file named "age.txt"

## Part 4: Loading Text Files with `np.loadtxt`
    - Using `np.loadtxt` to read text files and create arrays.



In [11]:
new_age = np.loadtxt("age.txt", delimiter=",")
new_age

array([18., 25., 33., 44., 22., 45.])


## Part 5: Additional Options and Parameters
    - Discussion of additional parameters like `delimiter`, `skiprows`, and `usecols`.

"skiprows" determines how many elements from the beginning you'll skip

In [29]:
new_age = np.loadtxt("age.txt", delimiter=",", skiprows=1) # skip the first element
new_age

array([25., 33., 44., 22., 45.])

In [28]:
new_age = np.loadtxt("age.txt", delimiter=",", skiprows=2) # skip the first two elements
new_age

array([33., 44., 22., 45.])